name: ci

on:
  push:
  pull_request:

jobs:
  configure:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup CMake & Ninja
        uses: lukka/get-cmake@v3
      - name: Configure (Debug)
        run: cmake -S . -B build/debug -G Ninja -DCSVQR_BUILD_TESTS=ON -DCSVQR_BUILD_BENCH=ON
